# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CodeSearch < Formula
  desc "Self-hosted code search and bulk operations across all your repositories"
  homepage "https://code-search.techquests.dev"
  version "1.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/techquestsdev/code-search/releases/download/v1.1.0/code-search_1.1.0_Darwin_x86_64.tar.gz"
      sha256 "c4aa89de9140a129003cddf225074682d69fa1b88a8d041d5f445f0afa108b41"

      define_method(:install) do
        bin.install "code-search"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/techquestsdev/code-search/releases/download/v1.1.0/code-search_1.1.0_Darwin_arm64.tar.gz"
      sha256 "c9dab0069b05a9b441bdb014f9db84bd9b9ebf19d598e671b2721973c2d2c908"

      define_method(:install) do
        bin.install "code-search"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/techquestsdev/code-search/releases/download/v1.1.0/code-search_1.1.0_Linux_x86_64.tar.gz"
      sha256 "5b0c9a57826901ee5f7420d2b39e88a8f6747a71acb719685410a59d0b01874c"
      define_method(:install) do
        bin.install "code-search"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/techquestsdev/code-search/releases/download/v1.1.0/code-search_1.1.0_Linux_arm64.tar.gz"
      sha256 "3a9105e66eda535c1fac744739c7d10db5f77740a6077945f298fff3449414d9"
      define_method(:install) do
        bin.install "code-search"
      end
    end
  end
end
