# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CodeSearch < Formula
  desc "Self-hosted code search and bulk operations across all your repositories"
  homepage "https://code-search.techquests.dev"
  version "1.0.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/techquestsdev/code-search/releases/download/v1.0.0/code-search_1.0.0_Darwin_x86_64.tar.gz"
      sha256 "f75bea5a9c88baf643105e50d3c1483ccffc2531de7e07a276bb3e0057bd2737"

      define_method(:install) do
        bin.install "code-search"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/techquestsdev/code-search/releases/download/v1.0.0/code-search_1.0.0_Darwin_arm64.tar.gz"
      sha256 "42a1be6a7e9abdaaccbdfffd8e9e19e150d22cd10feea2d0bcd53395d3d7891b"

      define_method(:install) do
        bin.install "code-search"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/techquestsdev/code-search/releases/download/v1.0.0/code-search_1.0.0_Linux_x86_64.tar.gz"
      sha256 "1aaadd3a3893d77246ff1cfda46f8416d8514b36414b112582f71980a4aa5287"
      define_method(:install) do
        bin.install "code-search"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/techquestsdev/code-search/releases/download/v1.0.0/code-search_1.0.0_Linux_arm64.tar.gz"
      sha256 "2ed2c5800ff4c4cfc2fc0ed0320f5efc377f2ccd37b937279bceb1db19088292"
      define_method(:install) do
        bin.install "code-search"
      end
    end
  end
end
