# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CrontabGuru < Formula
  desc "🕐 Interactive terminal-based cron expression editor built with Go and Bubble Tea"
  homepage "https://github.com/techquestsdev/crontab-guru"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/techquestsdev/crontab-guru/releases/download/v1.0.0/crontab-guru_1.0.0_Darwin_x86_64.tar.gz"
      sha256 "60fbad84b294389afddb28613b555ab51c88985dcc6ad2cbd9234e89f2453306"

      def install
        bin.install "crontab-guru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/techquestsdev/crontab-guru/releases/download/v1.0.0/crontab-guru_1.0.0_Darwin_arm64.tar.gz"
      sha256 "ca439343cbf59e229d93a94bcbcaf4701b1fa1be323d85cb4512902dade42af2"

      def install
        bin.install "crontab-guru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/techquestsdev/crontab-guru/releases/download/v1.0.0/crontab-guru_1.0.0_Linux_x86_64.tar.gz"
      sha256 "0e0aec9eb026c01be54c4254a8d1ea1ba423b237891ae6c0f9ca8b67dd0abb20"
      def install
        bin.install "crontab-guru"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/techquestsdev/crontab-guru/releases/download/v1.0.0/crontab-guru_1.0.0_Linux_arm64.tar.gz"
      sha256 "7349da11bbf5101f653e26c492a617d4b37e806639b4cc9ed624ceafc124007a"
      def install
        bin.install "crontab-guru"
      end
    end
  end

  def caveats
    <<~EOS
      Crontab Guru is an interactive terminal application for creating and editing cron expressions.
      Keywords: cron, crontab, scheduler, terminal, TUI, CLI, bubbletea, interactive, developer-tools
    EOS
  end
end
