# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CrontabGuru < Formula
  desc "Interactive terminal-based cron expression editor built with Go and Bubble Tea"
  homepage "https://github.com/techquestsdev/crontab-guru"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/techquestsdev/crontab-guru/releases/download/v1.0.1/crontab-guru_1.0.1_Darwin_x86_64.tar.gz"
      sha256 "bb0f26016b6745f662d992011c382b29c6234c91e994d91be43f58b6aff56a9c"

      def install
        bin.install "crontab-guru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/techquestsdev/crontab-guru/releases/download/v1.0.1/crontab-guru_1.0.1_Darwin_arm64.tar.gz"
      sha256 "fdb19d72445811445f460fd2b258ce8c4882d3b9ab9a54afc08a4aadf1771637"

      def install
        bin.install "crontab-guru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/techquestsdev/crontab-guru/releases/download/v1.0.1/crontab-guru_1.0.1_Linux_x86_64.tar.gz"
      sha256 "cd0d3a2428754d3eca5fa27a29b18439470c4dd41ecf64a261bd63a7c1e0deef"
      def install
        bin.install "crontab-guru"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/techquestsdev/crontab-guru/releases/download/v1.0.1/crontab-guru_1.0.1_Linux_arm64.tar.gz"
      sha256 "bdfbbc2aa39fdd141d3b742cd64ac18a7e0b672bd4ba4545977928c616a70148"
      def install
        bin.install "crontab-guru"
      end
    end
  end

  def caveats
    <<~EOS
      Crontab Guru is an interactive terminal application for creating and editing cron expressions.
      Keywords: cron, crontab, scheduler, terminal, TUI, CLI, bubbletea, interactive, developer-tools
    EOS
  end
end
