# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CrontabGuru < Formula
  desc "Interactive terminal-based cron expression editor built with Go and Bubble Tea"
  homepage "https://github.com/techquestsdev/crontab-guru"
  version "1.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/techquestsdev/crontab-guru/releases/download/v1.0.2/crontab-guru_1.0.2_Darwin_x86_64.tar.gz"
      sha256 "0a3a622caa2e08c62a6ee75e7ffbc8770a55306367c6db14bf600df8aa642519"

      define_method(:install) do
        bin.install "crontab-guru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/techquestsdev/crontab-guru/releases/download/v1.0.2/crontab-guru_1.0.2_Darwin_arm64.tar.gz"
      sha256 "cae71e5e85693e288df93bd099a91a86c4bc16a7a30d6e02fd276d2ec4caffdd"

      define_method(:install) do
        bin.install "crontab-guru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/techquestsdev/crontab-guru/releases/download/v1.0.2/crontab-guru_1.0.2_Linux_x86_64.tar.gz"
      sha256 "ae9b16ed9255dd3c1ae67956d5eff2b7e1459e60ffda3810e88a4229c67c2248"
      define_method(:install) do
        bin.install "crontab-guru"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/techquestsdev/crontab-guru/releases/download/v1.0.2/crontab-guru_1.0.2_Linux_arm64.tar.gz"
      sha256 "b9e0c263f05303514977864ab3cf44c790be68473c561e613cbe386b0c6ed541"
      define_method(:install) do
        bin.install "crontab-guru"
      end
    end
  end

  def caveats
    <<~EOS
      Crontab Guru is an interactive terminal application for creating and editing cron expressions.
      Keywords: cron, crontab, scheduler, terminal, TUI, CLI, bubbletea, interactive, developer-tools
    EOS
  end
end
