# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitContext < Formula
  desc "A powerful CLI tool for managing multiple Git configuration profiles"
  homepage "https://github.com/techquestsdev/git-context"
  version "1.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/techquestsdev/git-context/releases/download/v1.4.0/git-context_1.4.0_Darwin_x86_64.tar.gz"
      sha256 "42e8ed76d7c71aa36463df3a891b03ad19eedf49cdea116470064025bcee40af"

      define_method(:install) do
        bin.install "git-context"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/techquestsdev/git-context/releases/download/v1.4.0/git-context_1.4.0_Darwin_arm64.tar.gz"
      sha256 "665d0668b49706bec3b438b369063538e7674ea6bf7f01d397043ecf796bd594"

      define_method(:install) do
        bin.install "git-context"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/techquestsdev/git-context/releases/download/v1.4.0/git-context_1.4.0_Linux_x86_64.tar.gz"
      sha256 "3821e8bbe8060114c30eecaaf7d01718c355709c0bdb420124c02bac91d9990b"
      define_method(:install) do
        bin.install "git-context"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/techquestsdev/git-context/releases/download/v1.4.0/git-context_1.4.0_Linux_arm64.tar.gz"
      sha256 "41aafd154e08c4113f70405358de9e00b8e812dcc0df9555a01faec48cba3fcf"
      define_method(:install) do
        bin.install "git-context"
      end
    end
  end

  def caveats
    <<~EOS
      Git Context is a command-line tool for managing multiple Git configuration profiles.
      Switch between different Git identities (work, personal, school, etc.) with a single command.
      Keywords: git, configuration, profiles, CLI, developer-tools, identity-management
    EOS
  end
end
