# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitContext < Formula
  desc "A powerful CLI tool for managing multiple Git configuration profiles"
  homepage "https://github.com/techquestsdev/git-context"
  version "1.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/techquestsdev/git-context/releases/download/v1.4.1/git-context_1.4.1_Darwin_x86_64.tar.gz"
      sha256 "e9a176009ce92bd905687fea459b702e036136ff311d3030e0013a8d232140e8"

      define_method(:install) do
        bin.install "git-context"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/techquestsdev/git-context/releases/download/v1.4.1/git-context_1.4.1_Darwin_arm64.tar.gz"
      sha256 "23b773d3d41d3540bca15c41950555b3e615747f1a5eb90c8e5569287c63bd44"

      define_method(:install) do
        bin.install "git-context"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/techquestsdev/git-context/releases/download/v1.4.1/git-context_1.4.1_Linux_x86_64.tar.gz"
      sha256 "209591715c4cea85096f365573f12698a7e5d4d33f50b8f8c15f1409221aa782"
      define_method(:install) do
        bin.install "git-context"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/techquestsdev/git-context/releases/download/v1.4.1/git-context_1.4.1_Linux_arm64.tar.gz"
      sha256 "711bf2ac045c510cdd94a3ebf40db71f6e0b4c1f2b1c3d48c36a9355a938d5ad"
      define_method(:install) do
        bin.install "git-context"
      end
    end
  end

  def caveats
    <<~EOS
      Git Context is a command-line tool for managing multiple Git configuration profiles.
      Switch between different Git identities (work, personal, school, etc.) with a single command.
      Keywords: git, configuration, profiles, CLI, developer-tools, identity-management
    EOS
  end
end
