# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitContext < Formula
  desc "A powerful CLI tool for managing multiple Git configuration profiles"
  homepage "https://github.com/techquestsdev/git-context"
  version "1.4.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/techquestsdev/git-context/releases/download/v1.4.3/git-context_1.4.3_Darwin_x86_64.tar.gz"
      sha256 "6139fde6566916884c0f57431f3a4df766ac1d2ec7066435da289897123780b7"

      define_method(:install) do
        bin.install "git-context"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/techquestsdev/git-context/releases/download/v1.4.3/git-context_1.4.3_Darwin_arm64.tar.gz"
      sha256 "a48e7857928d21b0d6bd79f7056fc99e26afc81bde332a720997d1722cf17d98"

      define_method(:install) do
        bin.install "git-context"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/techquestsdev/git-context/releases/download/v1.4.3/git-context_1.4.3_Linux_x86_64.tar.gz"
      sha256 "86be156d9b4dd721c9f898727e3de2ac36f1769ac9ee5496078d43626950de37"
      define_method(:install) do
        bin.install "git-context"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/techquestsdev/git-context/releases/download/v1.4.3/git-context_1.4.3_Linux_arm64.tar.gz"
      sha256 "2642344506eeeaf1bf051b9d756d25838c43bf11b2d01c493502d8a54b999a08"
      define_method(:install) do
        bin.install "git-context"
      end
    end
  end

  def caveats
    <<~EOS
      Git Context is a command-line tool for managing multiple Git configuration profiles.
      Switch between different Git identities (work, personal, school, etc.) with a single command.
      Keywords: git, configuration, profiles, CLI, developer-tools, identity-management
    EOS
  end
end
