# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Howto < Formula
  desc "AI-powered command-line assistant for shell commands"
  homepage "https://github.com/techquestsdev/howto"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/techquestsdev/howto/releases/download/v1.1.0/howto_1.1.0_Darwin_x86_64.tar.gz"
      sha256 "89a3ddcdc09f0c776aad5dd3276c5d759e4569ad90e65be2d3a36e5db503afbb"

      define_method(:install) do
        bin.install "howto"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/techquestsdev/howto/releases/download/v1.1.0/howto_1.1.0_Darwin_arm64.tar.gz"
      sha256 "9dd45c36d77033b11f22d6f17097671e1c5900f03bd8dd0a8b35cb387e549892"

      define_method(:install) do
        bin.install "howto"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/techquestsdev/howto/releases/download/v1.1.0/howto_1.1.0_Linux_x86_64.tar.gz"
      sha256 "ebfa89a73697decbcfff77456639315c5be345e2df4fa32805ff4f0e2c28ffd9"
      define_method(:install) do
        bin.install "howto"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/techquestsdev/howto/releases/download/v1.1.0/howto_1.1.0_Linux_arm64.tar.gz"
      sha256 "ee8e7bc76c3e1cedb5f561b7804011f964059586b878cb2d9913ab44fd4d2920"
      define_method(:install) do
        bin.install "howto"
      end
    end
  end

  def caveats
    <<~EOS
      Howto is an AI-powered command-line tool that suggests shell commands.
      Set your API key to get started:
        export OPENAI_API_KEY=your-key    # For OpenAI
        export ANTHROPIC_API_KEY=your-key # For Anthropic/Claude
        export GEMINI_API_KEY=your-key    # For Google Gemini
        export GITHUB_TOKEN=your-token    # For GitHub Copilot

      Usage: howto "your natural language query"
    EOS
  end
end
