# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Howto < Formula
  desc "AI-powered command-line assistant for shell commands"
  homepage "https://github.com/techquestsdev/howto"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/techquestsdev/howto/releases/download/v1.0.0/howto_1.0.0_Darwin_x86_64.tar.gz"
      sha256 "ff0e42bb99392890dc050e7b3491888ecef985a619d581890c28f871168db828"

      def install
        bin.install "howto"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/techquestsdev/howto/releases/download/v1.0.0/howto_1.0.0_Darwin_arm64.tar.gz"
      sha256 "7e8f4e826af6a39139622ff365406283ed790898c6efc747bfa83193cb4a0114"

      def install
        bin.install "howto"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/techquestsdev/howto/releases/download/v1.0.0/howto_1.0.0_Linux_x86_64.tar.gz"
      sha256 "93d929e434f496715465747c884e9fdaf24b3cf8a0cada46e9843e4544c09273"
      def install
        bin.install "howto"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/techquestsdev/howto/releases/download/v1.0.0/howto_1.0.0_Linux_arm64.tar.gz"
      sha256 "7661dc35e0eb5d213b947dab78f86ea65f46900798a4f6bd0d2753879819fc8a"
      def install
        bin.install "howto"
      end
    end
  end

  def caveats
    <<~EOS
      Howto is an AI-powered command-line tool that suggests shell commands.
      Set your API key to get started:
        export OPENAI_API_KEY=your-key    # For OpenAI
        export ANTHROPIC_API_KEY=your-key # For Anthropic/Claude
        export GEMINI_API_KEY=your-key    # For Google Gemini
        export GITHUB_TOKEN=your-token    # For GitHub Copilot

      Usage: howto "your natural language query"
    EOS
  end
end
